name: Encrypt Your Password
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        run: |
          pip install -r requirements.txt
      - name: Run Flask App
        run: flask run --host 0.0.0.0

  deploy:
    runs-on: windows-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        run: |
          pip install -r requirements.txt
      - name: Run Flask App
        run: flask run --host 0.0.0.0